<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\Cobranzas\**" />
    <Compile Remove="Controllers\Emision\**" />
    <Content Remove="Controllers\Cobranzas\**" />
    <Content Remove="Controllers\Emision\**" />
    <EmbeddedResource Remove="Controllers\Cobranzas\**" />
    <EmbeddedResource Remove="Controllers\Emision\**" />
    <None Remove="Controllers\Cobranzas\**" />
    <None Remove="Controllers\Emision\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="customAppSettings.xml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="customAppSettings.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="8.1.1" />
    <PackageReference Include="ClosedXML" Version="0.95.4" />
    <PackageReference Include="EPPlus" Version="6.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="5.0.3" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="PDFsharp" Version="1.50.5147" />
    <PackageReference Include="SimpleImpersonation" Version="4.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.0.5" />
    <PackageReference Include="System.Data.OleDb" Version="5.0.0" />
    <PackageReference Include="System.DirectoryServices" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VidaCamara.CorssCuting.LoggerServices\VidaCamara.CrossCuting.Log.LoggerService.csproj" />
    <ProjectReference Include="..\VidaCamara.CrossCuting.Log.Contracts\VidaCamara.CrossCuting.Log.Contracts.csproj" />
    <ProjectReference Include="..\VidaCamara.CrossCuting.Utilities\VidaCamara.CrossCuting.Utilities.csproj" />
    <ProjectReference Include="..\VidaCamara.Domain.Services\VidaCamara.Domain.Services.csproj" />
    <ProjectReference Include="..\VidaCamara.Infrastructure.Data\VidaCamara.Infrastructure.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="VVSClave">
      <HintPath>..\VidaCamara.Infrastructure.Connection\VVSClave.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="templater.lic">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Templates\Correo\cabecera.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Templates\Correo\casa.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Templates\Correo\contacto.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Templates\Correo\EmisionPoliza.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Templates\Correo\facebook.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Templates\Correo\img1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Templates\Correo\img2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Templates\Correo\img3.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Templates\Correo\img4.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Templates\Correo\img5.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Templates\Correo\instagram.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Templates\Correo\linea.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Templates\Correo\linkedin.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Templates\Correo\logo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Templates\Correo\youtube.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resources\" />
  </ItemGroup>

	<ProjectExtensions>
		<VisualStudio>
			<UserProperties appsettings_1json__JsonSchema="" />
		</VisualStudio>
	</ProjectExtensions>

</Project>
