<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.95.4" />
    <PackageReference Include="FreeSpire.Doc" Version="7.11.0" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="5.2.7" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="5.0.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="5.0.0" />
    <PackageReference Include="Templater" Version="5.2.0" />
    <PackageReference Include="Twilio" Version="5.58.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VidaCamara.Domain.Services\VidaCamara.Domain.Services.csproj" />
  </ItemGroup>

</Project>
